import { Dongle } from "next/font/google";
import { Fredoka } from "next/font/google";
import { Work_Sans } from "next/font/google";
import { Adamina } from "next/font/google";
import "./globals.css";

const dongle = Dongle({
  variable: "--font-dongle",
  weight: "400",
  subsets: ["latin"],
});

const adamina = Adamina({
  variable: "--font-adamina",
  weight: "400",
  subsets: ["latin"],
});

const workSans = Work_Sans({
  variable: "--font-workSans",
  weight: "400",
  subsets: ["latin"],
});

const fredoka = Fredoka({
  variable: "--font-fredoka",
  weight: "400",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${dongle.variable} ${workSans.variable} ${fredoka.variable} ${adamina.variable} antialiased bg-blue`}
      >
        {children}
      </body>
    </html>
  );
}
