import { Dongle } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const dongle = Dongle({
  variable: "--font-dongle",
  weight: "400",
  subsets: ["latin"],
});

const riggle = localFont({
  src: '../../public/riggle.ttf',
  variable: '--font-custom'
})

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${riggle.variable} ${dongle.variable} antialiased bg-[#50B175]`}
      >
        {children}
      </body>
    </html>
  );
}
